xxxx

diff --git a/.github/workflows/deploy-QA.yml b/.github/workflows/deploy-QA.yml
--- a/.github/workflows/deploy-QA.yml
+++ b/.github/workflows/deploy-QA.yml
@@ -20,10 +20,12 @@ jobs:
         run: |
           fixed_version=$(echo "${{github.ref_name}}" | grep -Eo '[0-9].[0-9].[0-9]+')
           jira_fixed_version="React-Native SDK v$fixed_version"
-          echo "Getting jira tickets related to $jira_fixed_version"
           curl -X GET -H "Authorization: Basic bWF4aW1AYXBwc2ZseWVyLmNvbTp3Nk1OaGJSYUZsZnNhMXBiOEZkdzU3MDU=" https://appsflyer.atlassian.net/rest/api/3/project/11400/versions | jq -r '.[].name' | while read name ; do
             if [ "$name" == "$jira_fixed_version" ];then
-              echo "${name}"
+              echo "${name} Found!"
+            else
+              echo "${name} Is not found!"
+              exit 1
             fi
           done  
 
